#!/usr/bin/env bash

set -o errexit

if [[ $# != 2 ]]; then
	echo -e 'Usage:'
	echo -e '\tdjango-drop-create user database'
	exit 127
fi

charset='DEFAULT CHARACTER SET = ascii'
collation='DEFAULT COLLATE = ascii_general_ci'

mysqladmin -u $1 drop $2 || true
mysql -u $1 -e "CREATE DATABASE $2 $charset $collation" \
	&& yes no | ./manage.py syncdb && ./manage.py migrate
