#!/usr/bin/env bash
set -eu

if [[ $# != 1 ]]; then
    echo 'oh noes' >&2
    exit 10
fi

arc="$1"
zipstem="$(echo "$arc" | sed -E 's/(.*)\.[^.]*/\1/')"
tar --one-top-level -xf "$arc" || unzip -d "$zipstem" "$arc"
