file_list = {
    '.bashrc': '~',
    '.Rprofile': '~',
    '.shell-commonrc': '~',
    '.vimrc': '~',
    '.xmodmaprc': '~',
    '.zshrc': '~',
    '.zshrc-keys': '~',
    'cfg_notion.lua': '~/.notion/',
    'django-drop-create': '~/bin/',
    'drop-create': '~/bin/',
    'first': '~/bin/',
    'git-rr': '~/bin/',
    'ns': '~/bin/',
    'nse': '~/bin/',
}
