#!/usr/bin/env bash

if [[ -z "$1" ]]; then
	echo -e 'Usage:'
	echo -e '\tgit rr common_ancestor [old]'
fi

if [[ -z "$2" ]]; then
	other=ORIG_HEAD
else
	other=$2
fi

git diff-tree --no-commit-id --name-only -r $1 HEAD \
	| xargs -I {} bash -c "echo {}; colordiff <(git show :{}) <(git show ${other}:{}); echo"
