#!/usr/bin/env bash

if [[ $# != 2 ]]; then
	echo -e 'Usage:'
	echo -e '\tdjango-drop-create user database'
	exit 127
fi

mysqladmin -f -u $1 drop $2
mysqladmin -u $1 create $2 && yes no | ./manage.py syncdb \
	&& ./manage.py migrate
