#!/usr/bin/env bash

if [[ $# != 1 ]]; then exit; fi

first="$1"

R=$'\e[1;31m' #red
G=$'\e[1;32m' #green
Y=$'\e[1;33m' #yellow
B=$'\e[1;34m' #blue
P=$'\e[1;35m' #purple
C=$'\e[1;36m' #cyan
X=$'\e[0m' #no color


if [[ `id -u` == 0 ]]; then {
	sym="$Y#$X"
}; else {
	sym="$P\$$X"
}; fi


while true; do {
	echo -n "${G}[first]${X}${sym} ${C}$first${X} "
	read -r line
	if [[ $line == "" ]]; then {
		echo -n "Just run $first? [yN] "
		read -n 1 response
		if [[ $response == 'y' || $response == 'Y' ]]; then {
			echo
			$first
		}; elif [[ $response != "" ]]; then {
			echo
		}; fi
	}; else {
		$first $line
	}; fi
}; done
